# Site features
features_enabled:
  volunteer_directory: true
  resources: true
  office_hours: true
  success_stories: true

project_categories:
  - name: Medical
    slug: medical
    body: Support our overwhelmed health systems with medical innovation.
    project_types:
      - Scale testing
      - Medical facilities
      - Medical equipments
      - Treatment R&D
    color: purple
  - name: Prevention
    slug: prevention
    body: Inform, reduce, and control the spread of the outbreak.
    project_types:
      - Track the outbreak
      - Reduce spread
    color: orange
  - name: Community
    slug: community
    body: Work together to help our stressed communities.
    project_types:
      - E-Learning
      - Job placement
      - Mental health
      - Help out communities
      - Map volunteers to needs
      - News and information
      - Social giving
    color: blue
