colors:
  primary:
    50: '#e83a5d'
    100: '#e03255'
    200: '#d92b4e'
    300: '#d12346'
    400: '#c91b3e'
    500: '#c21437'
    600: '#ba0c2f'
    700: '#b20427'
    800: '#ab0020'
    900: '#a30018'
  secondary: '#000000'
